# Generated by Django 5.2.14 on 2026-05-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('explanation', models.TextField(max_length=500)),
                ('source', models.CharField(max_length=50)),
                ('cratedat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
