# Generated by Django 5.2.14 on 2026-05-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image',
            field=models.ImageField(default='', upload_to='blogs'),
        ),
    ]
