# Generated by Django 5.2.14 on 2026-05-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_login_alter_blogs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='last',
            field=models.CharField(max_length=50),
        ),
    ]
