# Generated by Django 5.2.14 on 2026-05-28 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_login_last'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='image',
        ),
    ]
