# Generated by Django 5.2.14 on 2026-05-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_login_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='last',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
    ]
